bot:
#  username: olzhastestbot
#  token: 5521006103:AAEpfMKvxON9Ek0CXKWctEZ1Sx4q70XPil8
  username: komek_stop_bullying_bot
  token: 7114292286:AAE_EvoY_wZKMxwtLYrMnDHlCPQEmFIT694
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aisulu_bot?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
