bot:
  username: komek_stop_bullying_bot
  token: 7114292286:AAE_EvoY_wZKMxwtLYrMnDHlCPQEmFIT694
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/komek_bot?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Syrbek2004@
  jpa:
    hibernate:
      ddl-auto: update